name: medibesti
description: A new Flutter project.

publish_to: 'none' # Prevent accidental publishing

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.8
  path_provider: ^2.1.3
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.4
  uuid: ^4.0.0
  flutter_chat_ui: ^1.6.7
  flutter_chat_types: ^3.6.2
  google_mlkit_text_recognition: ^0.15.0
  firebase_core: ^2.31.0
  cloud_firestore: ^4.15.0
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/onboarding/scan.png
    - lib/assets/onboarding/allergy.png
    - lib/assets/onboarding/notifications.png
    - lib/assets/onboarding/logo.png

